--- #YAML:1.0
name:                RadioMobile
version:             0.06
abstract:            A Perl interface to Radio Mobile .net file
license:             gpl
author:              
    - Emiliano Bruni <info@ebruni.it>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Array::AsObject:               0
    Class::Container:              0
    Class::MethodMaker:            0
    File::Binary:                  0
    IO::Scalar:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
