---
abstract: 'A Perl interface to Radio Mobile .net file'
author:
  - 'Emiliano Bruni <info@ebruni.it>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RadioMobile
no_index:
  directory:
    - t
    - inc
requires:
  Array::AsObject: 0
  Class::Container: 0
  Class::MethodMaker: 0
  File::Binary: 0
  IO::Scalar: 0
version: 0.10
